

def x3(age):
    open1 = open("x1.txt")
    x = open1.readlines()
    num = len(x)-1
    for i in x :
        open2 = open("x1.txt", "a")
        open2.write(f"{x[num][:-1]}{age}\n"
                    f"{x[num][:-1]}{age[0:1]}\n"
                    f"{x[num][:-1]}{age[0:2]}\n"
                    f"{x[num][:-1]}{age[1:2]}\n"
                    f"{x[num][:-1]}{age[2:3]}\n"
                    f"{x[num][:-1]}{age[3:4]}\n"
                    f"{x[num][:-1]}{age[2:4]}\n"
                    f"{x[num][:-1]}{age[4:6]}\n"
                    f"{x[num][:-1]}{age[6:8]}\n"
                    f"{x[num][:-1]}{age[4:8]}\n"
                    f"{x[num][:-1]}_{age}\n"     
                    f"{x[num][:-1]}_{age[0:1]}\n"
                    f"{x[num][:-1]}_{age[0:2]}\n"
                    f"{x[num][:-1]}_{age[1:2]}\n"
                    f"{x[num][:-1]}_{age[2:3]}\n"
                    f"{x[num][:-1]}_{age[3:4]}\n"
                    f"{x[num][:-1]}_{age[2:4]}\n"
                    f"{x[num][:-1]}_{age[4:6]}\n"
                    f"{x[num][:-1]}_{age[6:8]}\n"
                    f"{x[num][:-1]}_{age[4:8]}\n"
                    f"{x[num][:-1]}__{age}\n"      
                    f"{x[num][:-1]}__{age[0:1]}\n" 
                    f"{x[num][:-1]}__{age[0:2]}\n" 
                    f"{x[num][:-1]}__{age[1:2]}\n" 
                    f"{x[num][:-1]}__{age[2:3]}\n" 
                    f"{x[num][:-1]}__{age[3:4]}\n" 
                    f"{x[num][:-1]}__{age[2:4]}\n" 
                    f"{x[num][:-1]}__{age[4:6]}\n" 
                    f"{x[num][:-1]}__{age[6:8]}\n"
                    f"{x[num][:-1]}__{age[4:8]}\n"
                    f"{x[num][:-1]}##{age}\n"      
                    f"{x[num][:-1]}##{age[0:1]}\n" 
                    f"{x[num][:-1]}##{age[0:2]}\n" 
                    f"{x[num][:-1]}##{age[1:2]}\n" 
                    f"{x[num][:-1]}##{age[2:3]}\n" 
                    f"{x[num][:-1]}##{age[3:4]}\n" 
                    f"{x[num][:-1]}##{age[2:4]}\n" 
                    f"{x[num][:-1]}##{age[4:6]}\n" 
                    f"{x[num][:-1]}##{age[6:8]}\n"
                    f"{x[num][:-1]}##{age[4:8]}\n"
                    f"{x[num][:-1]}#{age}\n"      
                    f"{x[num][:-1]}#{age[0:1]}\n" 
                    f"{x[num][:-1]}#{age[0:2]}\n" 
                    f"{x[num][:-1]}#{age[1:2]}\n" 
                    f"{x[num][:-1]}#{age[2:3]}\n" 
                    f"{x[num][:-1]}#{age[3:4]}\n" 
                    f"{x[num][:-1]}#{age[2:4]}\n" 
                    f"{x[num][:-1]}#{age[4:6]}\n" 
                    f"{x[num][:-1]}#{age[6:8]}\n"
                    f"{x[num][:-1]}#{age[4:8]}\n"
                    f"{x[num][:-1]}-{age}\n"
                    f"{x[num][:-1]}-{age[0:1]}\n"
                    f"{x[num][:-1]}-{age[0:2]}\n"
                    f"{x[num][:-1]}-{age[1:2]}\n"
                    f"{x[num][:-1]}-{age[2:3]}\n"
                    f"{x[num][:-1]}-{age[3:4]}\n"
                    f"{x[num][:-1]}-{age[2:4]}\n"
                    f"{x[num][:-1]}-{age[4:6]}\n"
                    f"{x[num][:-1]}-{age[6:8]}\n"
                    f"{x[num][:-1]}-{age[4:8]}\n"
                    f"{x[num][:-1]}--{age}\n"
                    f"{x[num][:-1]}--{age[0:1]}\n"
                    f"{x[num][:-1]}--{age[0:2]}\n"
                    f"{x[num][:-1]}--{age[1:2]}\n"
                    f"{x[num][:-1]}--{age[2:3]}\n"
                    f"{x[num][:-1]}--{age[3:4]}\n"
                    f"{x[num][:-1]}--{age[2:4]}\n"
                    f"{x[num][:-1]}--{age[4:6]}\n"
                    f"{x[num][:-1]}--{age[6:8]}\n"
                    f"{x[num][:-1]}--{age[4:8]}\n"
                    f"{age}{x[num]}"                
                    f"{age[0:1]}{x[num]}"           
                    f"{age[0:2]}{x[num]}"           
                    f"{age[1:2]}{x[num]}"           
                    f"{age[2:3]}{x[num]}"           
                    f"{age[3:4]}{x[num]}"           
                    f"{age[2:4]}{x[num]}"           
                    f"{age[4:6]}{x[num]}"           
                    f"{age[6:8]}{x[num]}"           
                    f"{age[4:8]}{x[num]}"             
                    f"{age}_{x[num]}"               
                    f"{age[0:1]}_{x[num]}"          
                    f"{age[0:2]}_{x[num]}"          
                    f"{age[1:2]}_{x[num]}"          
                    f"{age[2:3]}_{x[num]}"          
                    f"{age[3:4]}_{x[num]}"          
                    f"{age[2:4]}_{x[num]}"          
                    f"{age[4:6]}_{x[num]}"          
                    f"{age[6:8]}_{x[num]}"          
                    f"{age[4:8]}_{x[num]}"            
                    f"{age}__{x[num]}"              
                    f"{age[0:1]}__{x[num]}"         
                    f"{age[0:2]}__{x[num]}"         
                    f"{age[1:2]}__{x[num]}"         
                    f"{age[2:3]}__{x[num]}"         
                    f"{age[3:4]}__{x[num]}"         
                    f"{age[2:4]}__{x[num]}"         
                    f"{age[4:6]}__{x[num]}"         
                    f"{age[6:8]}__{x[num]}"         
                    f"{age[4:8]}__{x[num]}"          
                    f"{age}##{x[num]}"              
                    f"{age[0:1]}##{x[num]}"         
                    f"{age[0:2]}##{x[num]}"         
                    f"{age[1:2]}##{x[num]}"         
                    f"{age[2:3]}##{x[num]}"         
                    f"{age[3:4]}##{x[num]}"         
                    f"{age[2:4]}##{x[num]}"         
                    f"{age[4:6]}##{x[num]}"         
                    f"{age[6:8]}##{x[num]}"         
                    f"{age}##{x[num]}"           
                    f"{age}#{x[num]}"               
                    f"{age[0:1]}#{x[num]}"          
                    f"{age[0:2]}#{x[num]}"          
                    f"{age[1:2]}#{x[num]}"          
                    f"{age[2:3]}#{x[num]}"          
                    f"{age[3:4]}#{x[num]}"          
                    f"{age[2:4]}#{x[num]}"          
                    f"{age[4:6]}#{x[num]}"          
                    f"{age[6:8]}#{x[num]}"          
                    f"{age[4:8]}#{x[num]}"
                    f"{age}-{x[num]}"
                    f"{age[0:1]}-{x[num]}"          
                    f"{age[0:2]}-{x[num]}"          
                    f"{age[1:2]}-{x[num]}"          
                    f"{age[2:3]}-{x[num]}"          
                    f"{age[3:4]}-{x[num]}"          
                    f"{age[2:4]}-{x[num]}"          
                    f"{age[4:6]}-{x[num]}"          
                    f"{age[6:8]}-{x[num]}"          
                    f"{age[4:8]}-{x[num]}" 
                    f"{age}--{x[num]}"
                    f"{age[0:1]}--{x[num]}"         
                    f"{age[0:2]}--{x[num]}"         
                    f"{age[1:2]}--{x[num]}"         
                    f"{age[2:3]}--{x[num]}"         
                    f"{age[3:4]}--{x[num]}"         
                    f"{age[2:4]}--{x[num]}"         
                    f"{age[4:6]}--{x[num]}"         
                    f"{age[6:8]}--{x[num]}"         
                    f"{age[4:8]}--{x[num]}")

        num -=1
        open2.close()
    num -=1
    open2.close()
    open1.close()
    from termcolor import colored
    return (colored("      setup 7/18 is completed     ","red"))


